version: '3'
services:
  test-ros-dev-container:
    stdin_open: true
    tty: true
    # command: tail -f /dev/null
    command: zsh -c "roscore"
    image: dev-ros-test-container:noetic
    build:
      context: .
      dockerfile: docker/Dockerfile
    
    user: "${UID}:${GID}"
    volumes:
      - $HOME/repo/test-dev-container:/home/user/test-dev-container